# Generated by Django 2.2.12 on 2021-05-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='age',
            field=models.IntegerField(),
        ),
    ]
