# Generated by Django 3.1.7 on 2021-03-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('capital', models.CharField(max_length=600)),
                ('population', models.IntegerField()),
                ('currency', models.CharField(max_length=600)),
                ('languages', models.CharField(max_length=600)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('neighbours', models.CharField(max_length=600, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.region')),
                ('subRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.subregion')),
            ],
        ),
    ]
