# Generated by Django 3.1.7 on 2021-03-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, unique=True)),
                ('region', models.CharField(max_length=600)),
                ('subRegion', models.CharField(max_length=600)),
                ('population', models.IntegerField()),
                ('currency', models.CharField(max_length=600)),
                ('languages', models.CharField(max_length=600)),
            ],
        ),
    ]
